apiVersion: v1
data:
  custom_parsers.conf: |
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

    [PARSER]
        Name go_go_3
        Format regex
        Regex (?<time>[^ ]+) \| (?<httpCode>[^ ]+) \|(\s)*(?<dur>[^ ]+) \| (?<ip>[^ ]+) \| (?<method>[^ ]+) \| (?<path>[^ ]+) \| (?<msg>.*)
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L

    [PARSER]
        Name go_go
        Format regex
        Regex [^ ](?<msg>[^ ].*)
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
  fluent-bit.conf: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri, go
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

    [INPUT]
        Name systemd
        Tag host.*
        Systemd_Filter _SYSTEMD_UNIT=kubelet.service
        Read_From_Tail On

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [OUTPUT]
        Name es
        Match kube.*
        Host 116.103.226.146
        Port 9200
        HTTP_User {username}
        HTTP_Passwd {password}
        Index huonglm_0327182170
        Generate_ID On
        Suppress_Type_Name On
        tls On
        tls.verify Off
        Logstash_Format On
        Logstash_Prefix huonglm_0327182170
        Retry_Limit False

    [OUTPUT]
        Name es
        Match host.*
        Host 116.103.226.146
        Port 9200
        HTTP_User elastic
        HTTP_Passwd iRsUoyhqW-CyyGdwk6V_
        Index huonglm_0327182170
        Suppress_Type_Name On
        tls On
        tls.verify Off
        Logstash_Format On
        Logstash_Prefix huonglm_0327182170
        Retry_Limit False

    [OUTPUT]
        Name es
        Match go-go.*
        Host 116.103.226.146
        Port 9200
        HTTP_User elastic
        HTTP_Passwd iRsUoyhqW-CyyGdwk6V_
        Index huonglm_0327182170
        Suppress_Type_Name On
        tls On
        tls.verify Off
        Logstash_Format On
        Logstash_Prefix huonglm_0327182170
        Retry_Limit False
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: fluent-bit
    meta.helm.sh/release-namespace: go-go
  creationTimestamp: "2024-06-12T11:39:14Z"
  labels:
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 3.0.6
    helm.sh/chart: fluent-bit-0.46.9
  name: fluent-bit
  namespace: go-go
  resourceVersion: "315512"
  uid: 3ddefa2b-c3ba-45fc-9b75-de516389ae86