apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: server-go-servicemonitor
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: "3000"
      path: /metrics
      interval: 15s
  selector:
    matchLabels:
      io.kompose.service: server-go
