apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: go-go
spec:
  type: NodePort
  ports:
    - name: web
      nodePort: 31174
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    managed-by: prometheus-operator
    operated-prometheus: "true"
